import { type Component } from "solid-js";
import { RandomStringinator } from "../util/randomString";

const FlavorText: Component = () => {
  const stringOpts = [
    `one of the websites of all time`,
    `windows? more like winBLOWS haha LOL!!!!!`,
    `rock005.mdl`,
    `my fumking fromsting`,
    `cabbage`,
    `HUH???`,
    `:3`,
    `severe thunderstorm warning`,
    `CLEARLY you don't own an airfryer`,
    `THEN WHO WAS PHONE?`,
    `\${flavorText}`,
    `drink some water`,
    `stay hydrated!`,
    `*yru'oe`,
    `nights at five freddies`,
    `five fredies at night`,
    `friday night fredies`,
    `fuck`,
    `don't care mate`,
    `no`,
    `ajdfhdklfghj`,
    `ow`,
    `ouch`,
    `omg hiii!!!!!!`,
    `buals`,
    `sharkaccino (real)`,
    `lead poisoning enthusiast`,
    `now with 50% more lead!`,
    `mmmmmmmmmmm`,
    `batteries not included`,
    `can i get uhhhhh`,
    `MAX_CALL_STACK_EXCEEDED`,
    `STATUS: eating chair foam`,
    `#1 tire rubber consumer`,
    `screen space ambient occlusion`,
    `3 dollars`,
    `ROCK AND STONE`,
    `new york times bestseller (pending review)`,
    `OH GREAT HEAVENS`,
    `this will be graphics in 2013`,
    `OHH MY PKCELLS`,
    `trans rights are human rights`,
    `🍄 have a fungus`,
    `a dink hard donk`,
    `really large solvent`,
    `evil hay sludge`,
    `sentenced to 10 minutes of twitter`,
    `i to am in this episode`,
    `this vexes me`,
    `THE MONEY`,
    `baja blastrogen`,
    `real`,
    `free money (download now)`,
    `girl bye`,
    `wahoo!`,
    `extremely normal`,
    `financial crisis`,
    `LIVE SHARK REACTION:`,
    `uuhguahg? ? sjidj efu :(`,
    `lumbago`,
    `cave3.ogg`,
    `who cares`,
    `hold shark gentle like hamburger`,
    `sharg`,
    `shork`,
    `the sharp`,
    `jeff jeeff 21 bruh *vine thud sound effec`,
    `wAUGH`,
    `NEW OBJECTIVE: open vscode without crying`,
    `DON'T MIND IF I DO`,
    `nuh uh`,
    `blunder artist`,
    `girl with computer`, 
    `NO WAY`,
    `caveman murals to mp4 converter`,
    `7/11 gasoline hits different`,
    `<-- she just ate 7 hamburgers`,
    `charcoal bread`,
    `olive garden for the nintendo 64`,
    `true cohost has never been tried`,
    `MY TOUYS`,
    `we've updated our privacy policy`,
    `by talos this cant be happening`,
    `gGogle.com Corn bread`,
    `#shitpit`,
    `operation: fortnite chungus`,
    `fart simpson`,
    `intel can eat my jorts`,
    `ongoing concern`,
    `you are now shoes`,
    `conk`,
    `more like LAME awards LOL!!!!!`,
    `what if software just FUCKING SUCKED!!!!!!!`,
    `Gender`,
    `poob has it for you`,
    `hot dog`,
    `NOW'S YOUR CHANCE TO TAKE A [[BIG SHIT]]`,
    `i bitign you`,
    `WOULD YOU LIKE TO EXPLODE?`,
    `executive dysfunction`,
    `bite this onions`,
    `macking cheese`,
    `girls kissing`,
    `im goin powder mode`,
    `THERE IS NO FRIDGE`,
    `Betle of people with alion`,
    `you have to install burger first`,
    `FUCK IM FALLING DOWN ALL THESE STAIRS .....`,
    `Lol *blows up your house*`,
    `lo-fi nuclear war to relax and study to`,
    `gaming diaper`,
    `THE ELECTRIC BILL`,
    `🚗 <- spormts car`,
    `java.lang.NullPointerException`,
    `give me your wallet`,
    `バーガーキング フットレタス`,
    `can i borrow ur phone`,
    `this is so epic`,
    `now available in 3 additional flavors`,
    `lol`,
    `lmao`,
    `lol. Lmao`,
    `psp exclusive`,
    `i cant read`,
    `i am functionally illiterate`,
    `[hilarious joke]`,
    `javascript, also known as java for short,`,
    `fucking uuugghhhhhh`,
    `you're aren't (epic backflip)`,
    `stinky`,
    `hamgruber macdronads`,
    `sign up now to get a free shoe (limit 1 per customer)`,
    `now in vr`,
    `grisps you`,
    `one time i ate a bagel`,
    `barbecue sauce`,
    `please drink verification can to continue`,
    `ok`,
    `women are so cool`,
    `i love you`,
    `9999999999999999`,
    `barcodes be like ||||||||||||||`,
    `gah damn`,
    `windows xp shutdown soudn effect`,
    `rebased and mergepilled`
  ];

  const stringinator = new RandomStringinator(stringOpts);

  const onClick = () => {
    // need to put this in it's own function
    // otherwise "this" keyword doesn't work correctly
    stringinator.refresh()
  }

  return (
    <a 
      href="javascript:void(0)" 
      onclick={onClick}
    >{stringinator.getCurrentString()}</a>
  )
}

export default FlavorText;